version: '3.8'

services:
  bot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
    volumes:
      - ./app:/inkohx/app/discordjs-share-chat/data
